import mock from 'mock-require';
mock('env', {}); // Mock env alias generated by wasm-pack

import { wasm_cross_transpile, wasm_parse_to_asl, default as init } from './apps/shared/src/lib/wasm/neuroforge_asl.js';
import { readFileSync } from 'fs';

async function verifyFrontendIntegration() {
    console.log("== NeuroForge Frontend <-> Rust WASM Integration Test ==");
    
    // 1. Initialize the generated WASM binary
    try {
        const wasmBuffer = readFileSync('./apps/shared/src/lib/wasm/neuroforge_asl_bg.wasm');
        await init(wasmBuffer);
        console.log("[\u2713] WASM Module cleanly initialized.");
    } catch (e) {
        console.error("[x] Failed to load WASM binary:", e);
        process.exit(1);
    }

    // 2. Validate ASL Tree parsing pipeline
    try {
        const exampleC = "void setup() { delay(100); }\nvoid loop() {}";
        const jsonResult = wasm_parse_to_asl(exampleC, "c");
        
        // Assert json structure matches AstProgram
        const data = JSON.parse(jsonResult);
        if (data.asl_version !== "4.0.0" || !Array.isArray(data.tasks)) {
            throw new Error(`Invalid ASL tree schema structure returned: ${jsonResult.substring(0, 50)}...`);
        }
        console.log("[\u2713] ASL Parsing successfully passed. AST structural serialization conforms to Universal ASL Standard v4.");
    } catch (e) {
        console.error("[x] ASL Tree parse integration failed:", e);
        process.exit(1);
    }

    // 3. Validate Transpilation pipeline (Rosetta cross compatibility)
    try {
        const exampleRust = "fn setup() {}\nfn loop() { digitalRead(4); }";
        const generatedPython = wasm_cross_transpile(exampleRust, "rust", "python");
        
        if (!generatedPython.includes("def loop():") || !generatedPython.includes("digitalRead(4)")) {
            throw new Error(`Python generator missing structural mappings! Yielded: \n${generatedPython}`);
        }
        console.log("[\u2713] Cross-transpilation Engine correctly passed Rust -> Universal ASL -> Python pipeline.");
    } catch (e) {
        console.error("[x] Cross Transpilation integration failed:", e);
        process.exit(1);
    }
    
    console.log("== ALL FRONTEND INTEGRATION TESTS PASSED ==");
}

verifyFrontendIntegration().catch(console.error);
