//! TOON Language Generator for NeuroForge ASL (v4.2)
//! 
//! [Config]    - Hardware and metadata
//! [Data]      - Global variables
//! [Structs]   - Data structures
//! [Functions] - Functional logic
//! [Setup]     - Initialization logic
//! [Loop]      - Cyclic behavior
//! [Events]    - Interrupts and event handlers

use crate::asl_types::{
    AslExpr, AslProgram, AslStatement, AslDuration,
    AslFor, PinModeKind,
};
use crate::plugins::core::generator::{AslGenerator, GeneratorOutput};

#[derive(Default)]
pub struct ToonGenerator {
    indent: usize,
}

impl ToonGenerator {
    pub fn new() -> Self {
        Self::default()
    }

    fn push_indent(&mut self) { self.indent += 2; }
    fn pop_indent(&mut self) { if self.indent >= 2 { self.indent -= 2; } }
    fn get_indent(&self) -> String { " ".repeat(self.indent) }

    pub fn generate_to_string(&mut self, program: &AslProgram) -> String {
        let mut output = String::new();
        output.push_str("// ASL v4.0.0 — Generated by NeuroForge Engine\n\n");
        self.generate_config(program, &mut output);
        output.push_str("\n");
        self.generate_data(program, &mut output);
        output.push_str("\n");
        self.generate_structs(program, &mut output);
        output.push_str("\n");
        self.generate_functions(program, &mut output);
        output.push_str("\n");
        self.generate_task_section("Setup", "setup", program, &mut output);
        output.push_str("\n");
        self.generate_events(program, &mut output);
        output.push_str("\n");
        self.generate_task_section("Loop", "loop", program, &mut output);
        output
    }

    fn generate_config(&self, program: &AslProgram, out: &mut String) {
        out.push_str("[Config]\n");
        if let Some(name) = &program.metadata.name { out.push_str(&format!("name: {}\n", name)); }
        if let Some(target) = &program.metadata.target_board { out.push_str(&format!("target: {}\n", target)); }
        for global in &program.globals {
            if global.name.to_lowercase().contains("pin") {
                let val = global.value.as_ref().map(|v| self.gen_expr(v)).unwrap_or_else(|| "0".to_string());
                out.push_str(&format!("{}: {}\n", global.name, val));
            }
        }
    }

    fn generate_data(&self, program: &AslProgram, out: &mut String) {
        let globals: Vec<_> = program.globals.iter().filter(|g| !g.name.to_lowercase().contains("pin")).collect();
        if !globals.is_empty() {
            out.push_str("[Data]\n");
            for g in globals {
                let val_str = g.value.as_ref().map(|v| self.gen_expr(v)).unwrap_or_else(|| "0".to_string());
                out.push_str(&format!("{}: {}\n", g.name, val_str));
            }
        }
    }

    fn generate_structs(&self, program: &AslProgram, out: &mut String) {
        if !program.structs.is_empty() {
            out.push_str("[Structs]\n");
            for s in &program.structs {
                out.push_str(&format!("struct {}:\n", s.name));
                for f in &s.fields { out.push_str(&format!("  - {}: {}\n", f.name, f.r#type.as_str())); }
            }
        }
    }

    fn generate_functions(&mut self, program: &AslProgram, out: &mut String) {
        if !program.functions.is_empty() {
            out.push_str("[Functions]\n");
            for f in &program.functions {
                let params: Vec<String> = f.params.iter().map(|p| format!("{}: {}", p.name, p.r#type.as_str())).collect();
                out.push_str(&format!("fn {}({}):\n", f.name, params.join(", ")));
                self.push_indent();
                for stmt in &f.body {
                    out.push_str(&self.get_indent());
                    out.push_str("- ");
                    self.generate_statement(stmt, out);
                    out.push_str("\n");
                }
                self.pop_indent();
            }
        }
    }

    fn generate_task_section(&mut self, title: &str, task_name: &str, program: &AslProgram, out: &mut String) {
        if let Some(task) = program.tasks.iter().find(|t| t.name == task_name) {
            out.push_str(&format!("[{}]\n", title));
            for stmt in &task.body {
                if matches!(stmt, AslStatement::AttachInterrupt(_)) { continue; }
                out.push_str("- ");
                self.generate_statement(stmt, out);
                out.push_str("\n");
            }
        }
    }

    fn generate_events(&mut self, program: &AslProgram, out: &mut String) {
        let mut interrupts = vec![];
        if let Some(setup) = program.tasks.iter().find(|t| t.name == "setup") {
            for stmt in &setup.body { if let AslStatement::AttachInterrupt(ai) = stmt { interrupts.push(ai); } }
        }
        if !interrupts.is_empty() {
            out.push_str("[Events]\n");
            for ai in interrupts {
                out.push_str(&format!("on_change({}):\n", self.gen_expr(&ai.pin)));
                out.push_str(&format!("  - {}()\n", ai.handler));
            }
        }
    }

    fn generate_statement(&mut self, stmt: &AslStatement, out: &mut String) {
        match stmt {
            AslStatement::PinMode(pm) => out.push_str(&format!("pinMode({}, {})", self.gen_expr(&pm.pin), self.gen_pin_mode(&pm.mode))),
            AslStatement::DigitalOutput(do_stmt) => out.push_str(&format!("digitalOutput({}, {})", self.gen_expr(&do_stmt.pin), self.gen_expr(&do_stmt.value))),
            AslStatement::Delay(d) => out.push_str(&format!("delay({})", self.gen_duration(&d.duration))),
            AslStatement::Print(p) => {
                let args: Vec<String> = p.args.iter().map(|a| self.gen_expr(a)).collect();
                out.push_str(&format!("print({})", args.join(", ")));
            }
            AslStatement::Assign(a) => out.push_str(&format!("{} = {}", a.target, self.gen_expr(&a.value))),
            AslStatement::Declare(d) => {
                let mut decl = if d.mutable { "let " } else { "const " }.to_string();
                decl.push_str(&d.name);
                if let Some(s) = &d.size {
                    decl.push_str(&format!("[{}]", self.gen_expr(s)));
                }
                if let Some(v) = &d.value {
                    decl.push_str(" = ");
                    decl.push_str(&self.gen_expr(v));
                }
                out.push_str(&decl);
            }
            AslStatement::If(if_stmt) => {
                out.push_str(&format!("if {}:\n", self.gen_expr(&if_stmt.condition)));
                self.push_indent();
                for s in &if_stmt.then_body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                self.pop_indent();
                for eif in &if_stmt.else_if {
                    out.push_str(&self.get_indent()); out.push_str(&format!("else if {}:\n", self.gen_expr(&eif.condition)));
                    self.push_indent();
                    for s in &eif.body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                    self.pop_indent();
                }
                if let Some(eb) = &if_stmt.else_body {
                    if !eb.is_empty() {
                        out.push_str(&self.get_indent()); out.push_str("else:\n");
                        self.push_indent();
                        for s in eb { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                        self.pop_indent();
                    }
                }
            }
            AslStatement::While(while_stmt) => {
                out.push_str(&format!("while {}:\n", self.gen_expr(&while_stmt.condition)));
                self.push_indent();
                for s in &while_stmt.body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                self.pop_indent();
            }
            AslStatement::Return(ret) => {
                out.push_str("return");
                if let Some(val) = &ret.value {
                    out.push_str(" ");
                    out.push_str(&self.gen_expr(val));
                }
            }
            AslStatement::Break => out.push_str("break"),
            AslStatement::Continue => out.push_str("continue"),
            AslStatement::For(for_enum) => {
                match &**for_enum {
                    AslFor::Range(r) => {
                        out.push_str(&format!("for ({} from {} to {} step {}):\n", r.var, self.gen_expr(&r.from), self.gen_expr(&r.to), self.gen_expr(&r.step)));
                        self.push_indent();
                        for s in &r.body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                        self.pop_indent();
                    }
                    AslFor::Each(e) => {
                        out.push_str(&format!("for ({} in {}):\n", e.var, self.gen_expr(&e.iterable)));
                        self.push_indent();
                        for s in &e.body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                        self.pop_indent();
                    }
                    AslFor::CStyle(c) => {
                        out.push_str(&format!("for ({}):\n", self.gen_expr(&c.condition)));
                        self.push_indent();
                        for s in &c.body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                        self.pop_indent();
                    }
                }
            }
            AslStatement::DoWhile(dw) => {
                out.push_str("do:\n");
                self.push_indent();
                for s in &dw.body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                self.pop_indent();
                out.push_str(&format!("while {}", self.gen_expr(&dw.condition)));
            }
            AslStatement::Switch(sw) => {
                out.push_str(&format!("switch {}:\n", self.gen_expr(&sw.discriminant)));
                self.push_indent();
                for case in &sw.cases {
                    out.push_str(&self.get_indent());
                    if let Some(val) = &case.test {
                        out.push_str(&format!("case {}:\n", self.gen_expr(val)));
                    } else {
                        out.push_str("default:\n");
                    }
                    self.push_indent();
                    for s in &case.body { out.push_str(&self.get_indent()); out.push_str("- "); self.generate_statement(s, out); out.push_str("\n"); }
                    self.pop_indent();
                }
                self.pop_indent();
            }
            AslStatement::AnalogOutput(ao) => out.push_str(&format!("analogOutput({}, {})", self.gen_expr(&ao.pin), self.gen_expr(&ao.value))),
            AslStatement::AnalogInput(ai) => out.push_str(&format!("analogInput({})", self.gen_expr(&ai.pin))),
            AslStatement::DigitalInput(di) => out.push_str(&format!("digitalInput({})", self.gen_expr(&di.pin))),
            AslStatement::SerialBegin(sb) => out.push_str(&format!("serialBegin({})", self.gen_expr(&sb.baud))),
            AslStatement::SerialWrite(sw) => out.push_str(&format!("serialWrite({})", self.gen_expr(&sw.data))),
            AslStatement::Comment(c) => out.push_str(&format!("// {}", c.text)),
            AslStatement::Expr(e) => out.push_str(&self.gen_expr(&e.expr)),
            _ => out.push_str(&format!("// [unsupported statement: {:?}]", stmt)),
        }
    }

    fn gen_expr(&self, expr: &AslExpr) -> String {
        match expr {
            AslExpr::Literal(l) => {
                if l.value.is_string() {
                    format!("\"{}\"", l.value.as_str().unwrap())
                } else if l.value.is_null() {
                    "null".to_string()
                } else {
                    l.value.to_string()
                }
            }
            AslExpr::Var(v) => v.name.clone(),
            AslExpr::Binary(b) => format!("({} {} {})", self.gen_expr(&b.left), b.op.to_symbol(), self.gen_expr(&b.right)),
            AslExpr::Unary(u) => format!("{}{}", u.op.to_symbol(), self.gen_expr(&u.expr)),
            AslExpr::Call(c) => {
                let args: Vec<String> = c.args.iter().map(|a| self.gen_expr(a)).collect();
                format!("{}({})", c.callee, args.join(", "))
            }
            AslExpr::Member(m) => format!("{}.{}", self.gen_expr(&m.target), m.property),
            AslExpr::Index(i) => format!("{}[{}]", self.gen_expr(&i.target), self.gen_expr(&i.index)),
            AslExpr::Conditional(c) => format!("({} ? {} : {})", self.gen_expr(&c.condition), self.gen_expr(&c.when_true), self.gen_expr(&c.when_false)),
            AslExpr::Cast(c) => format!("({}){}", c.target_type, self.gen_expr(&c.expr)),
            AslExpr::Array(a) => format!("{{ {} }}", a.elements.iter().map(|e| self.gen_expr(e)).collect::<Vec<_>>().join(", ")),
            AslExpr::PostfixInc(v) => format!("{}++", v),
            AslExpr::PostfixDec(v) => format!("{}--", v),
            _ => "expr".to_string(),
        }
    }

    fn gen_pin_mode(&self, mode: &PinModeKind) -> String {
        match mode {
            PinModeKind::Input => "INPUT".to_string(),
            PinModeKind::Output => "OUTPUT".to_string(),
            PinModeKind::InputPullup => "INPUT_PULLUP".to_string(),
            PinModeKind::InputPulldown => "INPUT_PULLDOWN".to_string(),
            PinModeKind::Analog => "ANALOG".to_string(),
            other => format!("{:?}", other).to_uppercase(),
        }
    }

    fn gen_duration(&self, d: &AslDuration) -> String {
        let mut units = vec![];
        if d.days > 0 { units.push(format!("{}d", d.days)); }
        if d.hours > 0 { units.push(format!("{}h", d.hours)); }
        if d.minutes > 0 { units.push(format!("{}m", d.minutes)); }
        if d.seconds > 0 { units.push(format!("{}s", d.seconds)); }
        if d.milliseconds > 0 { units.push(format!("{}ms", d.milliseconds)); }
        if d.microseconds > 0 { units.push(format!("{}us", d.microseconds)); }
        if units.is_empty() { return "0ms".to_string(); }
        units.join(", ")
    }
}

impl AslGenerator for ToonGenerator {
    fn generate(&mut self, program: &AslProgram) -> GeneratorOutput {
        GeneratorOutput::new(self.generate_to_string(program))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::neuro_parser::NeuroParser;
    use crate::plugins::python::python_parser::PythonParser;

    #[test]
    fn test_pir_motion_to_toon() {
        let py_code = r#"
from machine import Pin
import time

pir = Pin(14, Pin.IN)
led = Pin(15, Pin.OUT)

print("SYSTEM READY")

def pir_handler(pin):
    if pin.value() == 1:
        led.value(1)
        print("MOVEMENT DETECTED")
    else:
        led.value(0)
        print("NO MOVEMENT")

pir.irq(trigger=Pin.IRQ_RISING | Pin.IRQ_FALLING, handler=pir_handler)

while True:
    time.sleep(1)
"#;

        let program = PythonParser::parse(py_code).expect("Python parse failed");
        let mut gen = ToonGenerator::new();
        let toon = gen.generate_to_string(&program);
        
        println!("--- GENERATED TOON ---\n{}\n----------------------", toon);
        
        assert!(toon.contains("[Config]"));
        assert!(toon.contains("pir: 14"));
        assert!(toon.contains("led: 15"));
        assert!(toon.contains("fn pir_handler"));
        assert!(toon.contains("[Setup]"));
        assert!(toon.contains("on_change(pir)"));
    }
}
